baseURL = ""
languageCode = "en-us"
title = "My New Hugo Site"
theme = "wavo"
theme1 = "ananke"
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses            = true 
pygmentsStyle = "monokai"
ignoreLogs = ['warning-goldmark-raw-html']

[markup.goldmark.renderer]
unsafe = true